### ISSUE TITLE
'Avast Research Lab' dropdown under the 'Blogs' leads to a broken URL

### ISSUE THREAD

**Issue by Farial-mahmod** [avast/avast.github.io#5]
Description: The 'Blogs' tab on www.avast.com contains a dropdown named 'Avast Research Lab' which leads to https://gradient.avast.io/blog/ that shows no data.

Tested On:
1. Firefox on Windows 10 (version 116.2)
2. Safari on MacOS Ventura (version 16.5)

Solution: Populate the URL or replace with a new link.

Screenshots have been attached for better understanding.

![Safari-AVAST-BROKEN-LINK](https://github.com/avast/avast.github.io/assets/60639522/7219cc29-9459-47d4-ab55-08d49a9e45f3)

![avast-broken-link](https://github.com/avast/avast.github.io/assets/60639522/081ab06c-0caf-48a2-b0ac-1e490b110a16)

**Comment by mi-char** [comment]
Hi @Farial-mahmod. Thank you for reporting the issue. This repo is unrelated to both pages, www.avast.com, and gradient.avast.io, so I have reported the issue to the people managing the www.avast.com webpage, and I'm closing it here.

**Comment by Farial-mahmod** [comment]
Hello @mi-char , thank you for assisting. I could not find the repo of avast.com or gradient.avast.io where I could report.
